//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UsernamePasswordSecondFactor.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UsernamePasswordSecondFactor.Resources.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forms Authentication as Secondary Authentication.
        /// </summary>
        internal static string AdminFriendlyName {
            get {
                return ResourceManager.GetString("AdminFriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AuthenticationFailed.
        /// </summary>
        internal static string AuthenticationFailed {
            get {
                return ResourceManager.GetString("AuthenticationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div id=&quot;loginArea&quot;&gt;
        ///    &lt;script type=&quot;text/javascript&quot; language=&quot;JavaScript&quot;&gt;
        ///    //&lt;![CDATA[
        ///
        ///        function Login() {
        ///        }
        ///
        ///        Login.passwordInput = &apos;passwordInput&apos;;
        ///
        ///        Login.initialize = function () {
        ///
        ///        }();
        ///
        ///        Login.submitLoginRequest = function () { 
        ///
        ///            console.log(&quot;Start&quot;);
        ///            var password = document.getElementById(Login.passwordInput);
        ///
        ///            if (!password.value) {
        ///                return false;
        ///            }
        ///            con [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AuthPage {
            get {
                return ResourceManager.GetString("AuthPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChoiceFail.
        /// </summary>
        internal static string ChoiceFail {
            get {
                return ResourceManager.GetString("ChoiceFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChoiceSuccess.
        /// </summary>
        internal static string ChoiceSuccess {
            get {
                return ResourceManager.GetString("ChoiceSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forms Authentication as Secondary Authentication.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ErrorFailSelected.
        /// </summary>
        internal static string ErrorFailSelected {
            get {
                return ResourceManager.GetString("ErrorFailSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ErrorInvalidContext.
        /// </summary>
        internal static string ErrorInvalidContext {
            get {
                return ResourceManager.GetString("ErrorInvalidContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ErrorInvalidSessionId.
        /// </summary>
        internal static string ErrorInvalidSessionId {
            get {
                return ResourceManager.GetString("ErrorInvalidSessionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ErrorNoAnswerProvided.
        /// </summary>
        internal static string ErrorNoAnswerProvided {
            get {
                return ResourceManager.GetString("ErrorNoAnswerProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ErrorNoUserIdentity.
        /// </summary>
        internal static string ErrorNoUserIdentity {
            get {
                return ResourceManager.GetString("ErrorNoUserIdentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect password. Type the correct password, and try again..
        /// </summary>
        internal static string FailedLogin {
            get {
                return ResourceManager.GetString("FailedLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PageIntroductionText {
            get {
                return ResourceManager.GetString("PageIntroductionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your password.
        /// </summary>
        internal static string PageIntroductionTitle {
            get {
                return ResourceManager.GetString("PageIntroductionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PageTitle.
        /// </summary>
        internal static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        internal static string SubmitButtonLabel {
            get {
                return ResourceManager.GetString("SubmitButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserChoice.
        /// </summary>
        internal static string UserChoice {
            get {
                return ResourceManager.GetString("UserChoice", resourceCulture);
            }
        }
    }
}
